### ISSUE TITLE
Problem of  "compatibility_version" number. 

### ISSUE THREAD

**Issue by TitouanLazard** [rodionovd/machobot#3]
Hi,
You set  "cmd.current_version" and "cmd.compatibility_version" to 0x1000 by default. It set's the minimum version number of the library linked to 0.16.0. Libraries like frida-gadget.dylib only exist in version 0.0.0. It makes the binary crash when loading dylibs.
I fix the problem by replacing :
`cmd.current_version = cmd.compatibility_version = 0x1000`
to 
`cmd.current_version = cmd.compatibility_version = 0x0000`
in dylib.py

**Comment by rodionovd** [comment]
Fixed in #4 🫡
